//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Imports

import Foundation


// --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
// MARK: - Localizations


public struct Localizations {

    /// Base translation: Check-Out Date
    public static var CheckoutDateTitle : String = NSLocalizedString("CheckOut_Date_Title", comment: "")

    /// Base translation: Highest Price
    public static var FilterHighpriceTitle : String = NSLocalizedString("Filter_HighPrice_Title", comment: "")

    /// Base translation: Room Facility
    public static var FacilityRoomTitle : String = NSLocalizedString("Facility_Room_Title", comment: "")

    /// Base translation: Email
    public static var EmailFormData : String = NSLocalizedString("Email_Form_Data", comment: "")

    /// Base translation: Mr
    public static var MrFormData : String = NSLocalizedString("Mr_Form_Data", comment: "")

    /// Base translation: Highest Star
    public static var FilterHighstarTitle : String = NSLocalizedString("Filter_HighStar_Title", comment: "")

    /// Base translation: Please Confirm Data Is It True?
    public static var ConfirmdataTitle : String = NSLocalizedString("ConfirmData_Title", comment: "")

    /// Base translation: Pick Dates
    public static var PickDateTitleForm : String = NSLocalizedString("Pick_Date_Title_Form", comment: "")

    /// Base translation: Issued - %@
    public static func IssuedOrderTitle(_ value1 : String) -> String {
        return String(format: NSLocalizedString("Issued_Order_Title", comment: ""), value1)
    }

    /// Base translation: Hotel Facility
    public static var FacilityHotelTitle : String = NSLocalizedString("Facility_Hotel_Title", comment: "")

    /// Base translation: Including Breakfast
    public static var AvailablebreakfastTitle : String = NSLocalizedString("AvailableBreakfast_Title", comment: "")

    /// Base translation: Available Rooms: %@
    public static func AvailableroomTitle(_ value1 : String) -> String {
        return String(format: NSLocalizedString("AvailableRoom_Title", comment: ""), value1)
    }

    /// Base translation: Back
    public static var BackbuttonTitle : String = NSLocalizedString("BackButton_Title", comment: "")

    /// Base translation: Apply
    public static var ApplybuttonTitle : String = NSLocalizedString("ApplyButton_Title", comment: "")

    /// Base translation: Cancel
    public static var CancelbuttonTitle : String = NSLocalizedString("CancelButton_Title", comment: "")

    /// Base translation: Search Hotels
    public static var FindHotelTitle : String = NSLocalizedString("Find_Hotel_Title", comment: "")

    /// Base translation: Title
    public static var TitleFormData : String = NSLocalizedString("Title_Form_Data", comment: "")

    /// Base translation: Choose Payment
    public static var ChoosepaymentTitle : String = NSLocalizedString("ChoosePayment_Title", comment: "")

    /// Base translation: Order Hotel Room
    public static var OrderHotelTitle : String = NSLocalizedString("Order_Hotel_Title", comment: "")

    /// Base translation: %d Hotels Found
    public static func FilterHotelresultsTitle(_ value1 : Int) -> String {
        return String(format: NSLocalizedString("Filter_HotelResults_Title", comment: ""), value1)
    }

    /// Base translation: Not Included Breakfast
    public static var UnavailablebreakfastTitle : String = NSLocalizedString("UnavailableBreakfast_Title", comment: "")

    /// Base translation: Credit Card
    public static var CreditcardTitle : String = NSLocalizedString("CreditCard_Title", comment: "")

    /// Base translation: %d Guests
    public static func GuestPickTitle(_ value1 : Int) -> String {
        return String(format: NSLocalizedString("Guest_Pick_Title", comment: ""), value1)
    }

    /// Base translation: No
    public static var ConfirmnoTitle : String = NSLocalizedString("ConfirmNo_Title", comment: "")

    /// Base translation: %@ Guests
    public static func GuestTitle(_ value1 : String) -> String {
        return String(format: NSLocalizedString("Guest_Title", comment: ""), value1)
    }

    /// Base translation: Yes
    public static var ConfirmyesTitle : String = NSLocalizedString("ConfirmYes_Title", comment: "")

    /// Base translation: Guest Form
    public static var GuestContactFormTitle : String = NSLocalizedString("Guest_Contact_Form_Title", comment: "")

    /// Base translation: Maximum 15 Nights
    public static var MaximumNightsReminderTitle : String = NSLocalizedString("Maximum_Nights_Reminder_Title", comment: "")

    /// Base translation: Choose Check-In Date
    public static var CheckinPickTitle : String = NSLocalizedString("CheckIn_Pick_Title", comment: "")

    /// Base translation: %d Nights
    public static func CountNightsTitle(_ value1 : Int) -> String {
        return String(format: NSLocalizedString("Count_Nights_Title", comment: ""), value1)
    }

    /// Base translation: %d Rooms
    public static func RoomTitle(_ value1 : Int) -> String {
        return String(format: NSLocalizedString("Room_Title", comment: ""), value1)
    }

    /// Base translation: %@ per night
    public static func PricepernightHotelTitle(_ value1 : String) -> String {
        return String(format: NSLocalizedString("PricePerNight_Hotel_Title", comment: ""), value1)
    }

    /// Base translation: Price Total
    public static var PricetotalTitle : String = NSLocalizedString("PriceTotal_Title", comment: "")

    /// Base translation: Destination / Hotel
    public static var DestinationHotelTitleForm : String = NSLocalizedString("Destination_Hotel_Title_Form", comment: "")

    /// Base translation: This booking for someone else
    public static var AnotherguestOptionFormTitle : String = NSLocalizedString("AnotherGuest_Option_Form_Title", comment: "")

    /// Base translation: Lowest Price
    public static var FilterLowpriceTitle : String = NSLocalizedString("Filter_LowPrice_Title", comment: "")

    /// Base translation: Choose Check-Out Date
    public static var CheckoutPickTitle : String = NSLocalizedString("CheckOut_Pick_Title", comment: "")

    /// Base translation: Mrs
    public static var MrsFormData : String = NSLocalizedString("Mrs_Form_Data", comment: "")

    /// Base translation: Order Cart
    public static var CartOrdersTitle : String = NSLocalizedString("Cart_Orders_Title", comment: "")

    /// Base translation: Welcome to triptozero
    public static var WelcomeToTriptozero : String = NSLocalizedString("Welcome_To_TripToZero", comment: "")

    /// Base translation: First Name
    public static var FirstnameFormData : String = NSLocalizedString("FirstName_Form_Data", comment: "")

    /// Base translation: Guest & Room
    public static var GuestRoomTitleForm : String = NSLocalizedString("Guest_Room_Title_Form", comment: "")

    /// Base translation: Oops.. There's error a found. Please try again
    public static var ConfirmerrorTitle : String = NSLocalizedString("ConfirmError_Title", comment: "")

    /// Base translation: Order Id
    public static var OrderidTitle : String = NSLocalizedString("OrderId_Title", comment: "")

    /// Base translation: Phone Number
    public static var PhonenumberFormData : String = NSLocalizedString("PhoneNumber_Form_Data", comment: "")

    /// Base translation: Your Location
    public static var YourLocationTitle : String = NSLocalizedString("Your_Location_Title", comment: "")

    /// Base translation: Address
    public static var AddressHotelTitle : String = NSLocalizedString("Address_Hotel_Title", comment: "")

    /// Base translation: Payment Total: %@
    public static func PaytotalTitle(_ value1 : String) -> String {
        return String(format: NSLocalizedString("PayTotal_Title", comment: ""), value1)
    }

    /// Base translation: Ms
    public static var MsFormData : String = NSLocalizedString("Ms_Form_Data", comment: "")

    /// Base translation: Done
    public static var DonebuttonTitle : String = NSLocalizedString("DoneButton_Title", comment: "")

    /// Base translation: Choose Room
    public static var ChooseRoomTitle : String = NSLocalizedString("Choose_Room_Title", comment: "")

    /// Base translation: Filter
    public static var FilterButtonTitle : String = NSLocalizedString("Filter_Button_Title", comment: "")

    /// Base translation: Lowest Star
    public static var FilterLowstarTitle : String = NSLocalizedString("Filter_LowStar_Title", comment: "")

    /// Base translation: How Many Nights?
    public static var HowNightsTitle : String = NSLocalizedString("How_Nights_Title", comment: "")

    /// Base translation: Last Name
    public static var LastnameFormData : String = NSLocalizedString("LastName_Form_Data", comment: "")

    /// Base translation: Populer
    public static var FilterPopulerTitle : String = NSLocalizedString("Filter_Populer_Title", comment: "")

    /// Base translation: Book Room
    public static var OrderRoomTitle : String = NSLocalizedString("Order_Room_Title", comment: "")

    /// Base translation: Transfer
    public static var TransferTitle : String = NSLocalizedString("Transfer_Title", comment: "")

    /// Base translation: Only Maximum 15 Nights
    public static var MaximumNightsAlertTitle : String = NSLocalizedString("Maximum_Nights_Alert_Title", comment: "")

}